# ====================================
# Spring Boot Application Configuration (YAML)
# ====================================

spring:
  application:
    name: Book Catalog Application

  # Banner configuration
  banner:
    location: classpath:banner.txt

# Application version (custom property)
app:
  version: 1.0-SNAPSHOT

# ====================================
# Server Configuration
# ====================================
server:
  port: 8080
  servlet:
    context-path: /

  # Compression
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json

# ====================================
# Logging Configuration
# ====================================
logging:
  level:
    root: INFO
    com.bookapp: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  # File logging (optional)
  # file:
  #   name: logs/application.log
  #   max-size: 10MB
  #   max-history: 30

# ====================================
# Custom Application Properties
# ====================================
comments:
  max-author-length: 100
  max-text-length: 1000
  delete-allowed-hours: 24

pagination:
  default-size: 10
  max-size: 100

# ====================================
# Development Profile (optional)
# ====================================
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.bookapp: TRACE

server:
  port: 8081